### ISSUE TITLE
Move with Multiple Node Select

### ISSUE THREAD

**Issue by schae234** [LinkageIO/cob#71]
I can't move sets of genes when I ctrl+click and drag. Was this intentional?

**Comment by monprin** [comment]
I mean strictly speaking no, it would be default cytoscape behavior presumably, what is the use case for this?

**Comment by schae234** [comment]
I'd like to be able to select a group of genes so I can move them as a group. Sometimes the spring embedded layout gets a little ambitious and moves clusters very far away.

**Comment by monprin** [comment]
Alrighty I will take a look at this when I get home

**Comment by schae234** [comment]
OK, so shift+select DOES work, there is just no visual indication that multiple nodes were selected.

**Comment by monprin** [comment]
Well it doesn't appear that this sort of group movement is specifically supported in cytoscape.js. The closest thing I could come up with would be to use [this extension](https://github.com/cytoscape/cytoscape.js-automove) to build short term rules to move nodes in lockstep but I cannot come up with an elegant way to do this with the existing selection system in way that is intuitive to a user, especially since this isn't really what the extension appears to be designed for.

The obvious thing I could do (and probably will if you are okay with it) would be to make it so these boxes select nodes and highlight them as clicking does now. 

If you have an idea of how this interface could work in an intuitive way I'd be willing to look into it, but I can't figure out an elegant way to do this since it is not built into Cytoscape natively.

**Comment by schae234** [comment]
Well, if you select multiple nodes with the shift button you can move them as a group. Right now there doesn't appear to be any visual distinction for selected nodes (you do have rules for clicked nodes). I have a local version that fixes this.
