### ISSUE TITLE
Represent Chromosomes a Weighted Edges between SNPs

### ISSUE THREAD

**Issue by monprin** [LinkageIO/cob#9]
Change the logic so the entire layout can be derived from only a list of genes and connections. Option to override to insert correct chromosome lengths. This will slightly increase the computation overhead on the client (though it would simplify some stuff, so it'd most likely be quite small), but will make the layout much easier to use independent of this specific server and dataset.

Thoughts Rob?

**Comment by schae234** [comment]
I'm not sure I understand. What will change? How is it implemented right now? Genes should  be tied to parent SNPs right? How would you know how to pile genes into the sun "rays"?

**Comment by monprin** [comment]
Well sort of, but the SNPs have a habit of being so small and close together that they get merged in order to make the layout work. So instead of using the SNPs to build the bins, I could build them from the positions of the genes directly, the SNP labels would still be there for reference, but the combination SNPs would be built up from the genes directly.

Then I could do the same thing with chromosomes (It is basically what is happening on the server anyway), then this layout could be used with any set of just genes, which seems like it would be easier for other people to use should they care to because it simplifies the server quite a bit.

**Comment by schae234** [comment]
I think keeping SNPs separate is more important than accurately conveying the chromosome distances. The scale of distance between SNPs is going to vary so much that it just ins't informative. What **is** informative is knowing that genes originating from _different_ SNPs have an interaction. SNPs are the most informative unit we are dealing with here. Maybe displaying genes along the chromosomes as linear chunks isn't the best approach.

Instead of placing genes on the chromosome by their position can you space them proportionally along a 'virtual' chromosome. The space between SNPs can be the log of the distance between them. Then stack the candidate genes on top of them:

![img_20160519_120336](https://cloud.githubusercontent.com/assets/2566591/15402542/635d2a1e-1dba-11e6-95e8-2b04053cd937.jpg)

Nodes here are the "SNPs" not genes.

Does that make sense?

**Comment by monprin** [comment]
Okay, I sort of get what you are saying, but when they get laid out (especially on the more average size networks) is not that they are too clumped, it is a) that there are just too many to effectively show,since they will stack on top of each other, which is compounded by b) the vast majority SNPs have one (or maybe two) genes, thus eliminating the benefit of stacking them at all. The only solution I have come up with thus far is to clump the SNPs as a function of the diameter (in pixels) of the actual node image, which you can drop to one to get them into smaller bins. So I don't believe switching to relative distances between them would really help and it would further up the computational overhead on the client.

**Comment by monprin** [comment]
Is there another way we can clump SNPs that you're aware of?

**Comment by schae234** [comment]
I'm thinking that we might have to have different levels of resolution. I like the way that things are spread out right now in your collapsed SNP view. Instead of changing the layout, we should have **another** graph view that focuses on local interactions. I will come up with a mock and use case and open a separate issue on layout.

Otherwise, here is another thought. What if instead of the chromosome box, we had direct edges between SNPs and the edge weight (and tooltip) indicated the distance? Don't you already calculate x,y coordinates for each SNP?  If so, you could easily just not render the chromosome box, and use edge weights between SNPs which would effectively give you a chromosome looking thing with the added bonus of not having to render the box. 

Can we also make SNPs a different shape? Diamonds?

![img_20160524_095717](https://cloud.githubusercontent.com/assets/2566591/15508806/91af22fc-2196-11e6-9afb-fa57b2cee7e2.jpg)

**Comment by monprin** [comment]
The more I think about it, the more I like the multiple graph idea, but that and these are not mutually exclusive. and for some of the other ideas you've layed out:

## `ln(dist)` 

I have come to really think this would be a good idea, because there is more clumping on the chromosomes than I naively assumed, this would serve to minimize the number of SNP groups and still give some sense of scale. This can work with "Weighted Edges" (see below), but it would make it slightly less valuable, also this will make the layout more expensive. I don't have a through enough understanding to estimate how much of a tax this would be.

## Weighted Edges

As I said above this seems like a reasonable enough idea, though it may be made less valuable by the `ln` plan, but could work. I'd have to play around the specifics and how to somehow label the chromosomes on the graph since that node would mostly go away. This will also make layout more expensive, because it would add more complicated edges rather than a relatively simple polygon. I don't have a through enough understanding to estimate how much of a tax this would be.

## SNPG Shape

Since they are not autorotated around the circle, it looks a little weird, but if you think it'd be much more clear we can do that. If we did want to rotate them for each position, that would be expensive and annoying.

**Comment by schae234** [comment]
I'm glad that you are coming around to my ideas :+1: 

The multiple graph idea will be another issue/task completely. I just need to hammer out some details.

We can do the `ln(dist)` and the weighted edges right now though. The `ln` plan will be nice because SNPs wont overlap and we will still have a sense for scale (just not linear!) It'll just squish down the SNPs that are really far away. Yay for logarithms! 

It's actually complemented nicely with the weighted edges (well they in a sense encode the same information), in the fact that if we have actual edges between SNPs we can easily show labels. One useful piece of information we can include is a tooltip on the edge that contains the inter-SNP distance, which will be _really_ useful. That wasn't possible before and cannot be included using just coordinates for SNPs. 

I'm going to go ahead an change the label to Feature and include tasks!

**Comment by monprin** [comment]
I am going to hold off on the edge width for representing distance for awhile, the only way I am coming up with at the moment violate the norms of cytoscape, and also I think the other tasks provide more in the way of usefulness without being so much trouble. The ln(dist) is now completely implemented, and is able to be changed be a layout parameter, I will implement a toggle on the site for it when I am doing the others discussed in #17.

**Comment by schae234** [comment]
Hi Joe, I think we can close this issue for now. We can re-open it or refine it later if it fits our use cases.
